#include "sigma_delta_dac.h"
#include <Arduino.h>
#include <math.h>

#define sd_dac_buffer (g_sharedMem.dac_standalone)

static uint16_t sd_dac_buf_len = 0;
static bool sd_dac_running = false;
static bool s_isOscRunning = false;
static uint8_t sd_dac_prescaler = 0; // SPI BR field: 0 = /2 (42 MHz), 1 = /4 (21 MHz), ... 7 = /256 (328.125 kHz)

uint16_t sigma_delta_dac_get_max_buf_size() {
    return s_isOscRunning ? SD_DAC_DUAL_MAX_BUF_SIZE : SD_DAC_MAX_BUF_SIZE;
}

uint16_t sigma_delta_dac_get_buf_len() {
    return sd_dac_buf_len;
}

void sigma_delta_dac_prepare(uint8_t pin, uint16_t length, uint8_t prescalerExp) {
    (void)pin;
    sigma_delta_dac_stop();
    uint16_t maxAllowed = sigma_delta_dac_get_max_buf_size();
    if (length == 0 || length > maxAllowed) return;
    
    // Clear buffer to 0 (0V) instead of 0xAA (1.65V) to avoid DC offset before start
    memset(sd_dac_buffer, 0x00, length);
    
    sd_dac_buf_len = length;
    sd_dac_prescaler = (prescalerExp > 7) ? 7 : prescalerExp;
}

void sigma_delta_dac_init() {
    sd_dac_running = false;
    s_isOscRunning = false;
    sd_dac_buf_len = 0;
    memset(sd_dac_buffer, 0xAA, SD_DAC_MAX_BUF_SIZE);
}

void sigma_delta_dac_write_chunk(uint16_t offset, const uint8_t* data, uint16_t len) {
    if (!data || len == 0) return;
    uint16_t maxAllowed = sigma_delta_dac_get_max_buf_size();
    if (offset + len > maxAllowed) {
        len = (offset < maxAllowed) ? (maxAllowed - offset) : 0;
    }
    if (len > 0) {
        memcpy(&sd_dac_buffer[offset], data, len);
    }
}

void sigma_delta_dac_play() {
    uint16_t maxAllowed = sigma_delta_dac_get_max_buf_size();
    if (sd_dac_buf_len == 0 || sd_dac_buf_len > maxAllowed) return;

#if defined(ARDUINO_ARCH_STM32) && defined(SPI1)
    // 1. Enable Clocks
    RCC->APB2ENR |= RCC_APB2ENR_SPI1EN;
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN | RCC_AHB1ENR_GPIOBEN | RCC_AHB1ENR_DMA2EN;

    // 2. Configure PB5 Pin (AF5 - SPI1_MOSI @ 42 MHz)
    GPIOB->MODER   = (GPIOB->MODER   & ~(3U << (5 * 2))) | (2U << (5 * 2)); // AF Mode
    GPIOB->OSPEEDR = (GPIOB->OSPEEDR & ~(3U << (5 * 2))) | (3U << (5 * 2)); // Very High Speed
    GPIOB->AFR[0]  = (GPIOB->AFR[0]  & ~(15U << (5 * 4))) | (5U << (5 * 4)); // AF5 (SPI1_MOSI)
    
    // Always configure PA5 as SPI1_SCK (AF5) to keep the internal state machine happy
    GPIOA->MODER   = (GPIOA->MODER   & ~(3U << (5 * 2))) | (2U << (5 * 2)); // AF Mode
    GPIOA->OSPEEDR = (GPIOA->OSPEEDR & ~(3U << (5 * 2))) | (3U << (5 * 2)); // Very High Speed
    GPIOA->AFR[0]  = (GPIOA->AFR[0]  & ~(15U << (5 * 4))) | (5U << (5 * 4)); // AF5 (SPI1_SCK)

    // 3. Disable DMA & SPI before configuring to prevent hangs
    DMA2_Stream3->CR &= ~DMA_SxCR_EN;
    while (DMA2_Stream3->CR & DMA_SxCR_EN) {}
    SPI1->CR1 &= ~SPI_CR1_SPE;

    // 4. Configure SPI1 (Master, 8-bit, MSB first, prescaler from prepare)
    // CPOL=0, CPHA=0, DFF=0 (8-bit)
    SPI1->CR1 = SPI_CR1_MSTR | SPI_CR1_SSI | SPI_CR1_SSM | (sd_dac_prescaler << SPI_CR1_BR_Pos); 
    
    // CRITICAL: Configure SPI1 for Half-Duplex Transmit Only (1-line bidirectional, output enabled).
    // This physically disables the receiver, meaning the OVR flag will NEVER occur.
    SPI1->CR1 |= SPI_CR1_BIDIMODE | SPI_CR1_BIDIOE;
    
    // Enable SPI TX DMA request
    SPI1->CR2 = SPI_CR2_TXDMAEN;

    // 5. Configure DMA2 Stream 3 Channel 3 for SPI1 TX Circular DMA
    DMA2_Stream3->PAR  = (uint32_t)&(SPI1->DR);
    DMA2_Stream3->M0AR = (uint32_t)sd_dac_buffer;
    DMA2_Stream3->NDTR = sd_dac_buf_len;
    
    // DMA Configuration:
    // CHSEL = 3 (Channel 3 for SPI1_TX)
    // PL = 3 (Very High Priority)
    // MSIZE = 0 (8-bit), PSIZE = 0 (8-bit)
    // MINC = 1 (Memory Increment), PINC = 0 (Periph No Increment)
    // CIRC = 1 (Circular mode)
    // DIR = 1 (Memory-to-Peripheral)
    DMA2_Stream3->CR = (3U << DMA_SxCR_CHSEL_Pos) | 
                       (3U << DMA_SxCR_PL_Pos) | 
                       DMA_SxCR_MINC | 
                       DMA_SxCR_CIRC | 
                       (1U << DMA_SxCR_DIR_Pos);

    // CRITICAL: Clear all status flags for DMA2 Stream 3 before enabling!
    DMA2->LIFCR = DMA_LIFCR_CTCIF3 | DMA_LIFCR_CHTIF3 | DMA_LIFCR_CTEIF3 | DMA_LIFCR_CDMEIF3 | DMA_LIFCR_CFEIF3;
    
    // Clear any pending SPI errors by reading SR and DR
    (void)SPI1->SR;
    (void)SPI1->DR;

    // 6. Enable DMA Stream & SPI Peripheral
    DMA2_Stream3->CR |= DMA_SxCR_EN;
    SPI1->CR1 |= SPI_CR1_SPE;
#endif

    sd_dac_running = true;
}

#define SD_SINE_LUT_SIZE 256u
#define SD_SINE_AMPL 0.75f
#define SD_PI 3.14159265f

// Play a sine wave generated by a 2nd-order sigma-delta modulator directly on-device.
// Auto-selects the SPI prescaler (highest bit rate whose full-cycle fits the buffer)
// and a byte-aligned multi-cycle count for exact frequency.
void sigma_delta_dac_play_sine(uint8_t pin, uint32_t freqHz) {
    if (freqHz < 1) freqHz = 1;
    uint32_t maxBuf = sigma_delta_dac_get_max_buf_size();

    // 1. Pick SPI prescaler: highest bitrate with (bitrate / freq) <= buffer bits
    uint32_t exp = 7;
    for (uint32_t e = 0; e <= 7; e++) {
        uint32_t br = 84000000UL >> (e + 1);
        if (br / freqHz <= maxBuf * 8UL) { exp = e; break; }
    }
    const uint32_t bitrate = 84000000UL >> (exp + 1);
    uint32_t bpc = bitrate / freqHz; // bits per cycle (integer)
    if (bpc < 2) bpc = 2;
    if (bpc > maxBuf * 8UL) bpc = maxBuf * 8UL;

    // 2. Byte-aligned multi-cycle choice minimizing frequency error
    uint32_t maxK = (maxBuf * 8UL) / bpc;
    if (maxK < 1) maxK = 1;
    uint32_t bestBytes = maxBuf;
    uint32_t bestTotal = bpc;
    uint32_t bestK = 1;
    uint32_t bestErr = 0xFFFFFFFFu;
    for (uint32_t k = maxK; k >= 1; k--) {
        uint64_t want = (uint64_t)k * bpc;
        uint32_t bytes = (uint32_t)((want + 4) / 8);
        if (bytes == 0 || bytes > maxBuf) continue;
        uint32_t err = (bytes * 8u >= want) ? (uint32_t)(bytes * 8u - want) : (uint32_t)(want - bytes * 8u);
        if (err < bestErr) {
            bestErr = err;
            bestBytes = bytes;
            bestTotal = bytes * 8;
            bestK = k;
            if (err < 1) break;
        }
    }

    // 3. Generate into the DAC buffer (prepare() clears it first)
    sigma_delta_dac_prepare(pin, (uint16_t)bestBytes, (uint8_t)exp);

    static float sd_sin_lut[SD_SINE_LUT_SIZE];
    for (uint32_t i = 0; i < SD_SINE_LUT_SIZE; i++) {
        sd_sin_lut[i] = sinf(2.0f * SD_PI * (float)i / (float)SD_SINE_LUT_SIZE);
    }

    const uint32_t inc = (uint32_t)((16777216.0f * (float)bestK) / (float)bestTotal);

    float i1 = 0.0f, i2 = 0.0f, yp = 0.0f;
    for (uint32_t pass = 0; pass < 2; pass++) {
        uint32_t acc = 0;
        for (uint32_t i = 0; i < bestTotal; i++) {
            acc += inc;
            if (acc >= (1u << 24)) acc -= (1u << 24);
            const float x = SD_SINE_AMPL * sd_sin_lut[acc >> 16];
            i1 += x - yp;
            i2 += i1 - yp;
            const uint8_t bit = (i2 >= 0.0f) ? 1 : 0;
            yp = bit ? 1.0f : -1.0f;
            if (pass == 1) {
                if (bit) sd_dac_buffer[i >> 3] |= (uint8_t)(1u << (7 - (i & 7)));
            }
        }
    }

    // 4. Start DMA playback
    sigma_delta_dac_play();
}

void sigma_delta_dac_stop() {
    if (!sd_dac_running) return;

#if defined(ARDUINO_ARCH_STM32) && defined(SPI1)
    if (DMA2_Stream3->CR & DMA_SxCR_EN) {
        DMA2_Stream3->CR &= ~DMA_SxCR_EN;
        while (DMA2_Stream3->CR & DMA_SxCR_EN) {}
    }
    
    // Disable SPI and its DMA requests
    SPI1->CR2 &= ~SPI_CR2_TXDMAEN;
    SPI1->CR1 &= ~SPI_CR1_SPE;
#endif
    sd_dac_running = false;
}

// When Oscilloscope starts, clamp DAC buffer to 12 KB to avoid RAM collision with ADC
void sigma_delta_dac_on_osc_start() {
    s_isOscRunning = true;
    if (sd_dac_running && sd_dac_buf_len > SD_DAC_DUAL_MAX_BUF_SIZE) {
        sd_dac_buf_len = SD_DAC_DUAL_MAX_BUF_SIZE;
#if defined(ARDUINO_ARCH_STM32) && defined(SPI1)
        DMA2_Stream3->CR &= ~DMA_SxCR_EN;
        while (DMA2_Stream3->CR & DMA_SxCR_EN) {}
        DMA2_Stream3->NDTR = sd_dac_buf_len;
        DMA2->LIFCR = DMA_LIFCR_CTCIF3 | DMA_LIFCR_CHTIF3 | DMA_LIFCR_CTEIF3 | DMA_LIFCR_CDMEIF3 | DMA_LIFCR_CFEIF3;
        DMA2_Stream3->CR |= DMA_SxCR_EN;
#endif
    }
}

// When Oscilloscope stops, allow future DAC playback to use full 48 KB
void sigma_delta_dac_on_osc_stop() {
    s_isOscRunning = false;
}
